{
    //   id: 1,
    //   image1: 'assets/imgs/itens/vestido TITANIC.jpg',
    //   // image2: 'assets/imgs/itens/vestido TITANIC3.jpg',
    //   name: 'Vestido rose',
    //   movie: 'Titanic',
    //   description: 'vestido usado pela personagem nas cenas x, x e x',
    //   price: 500.0,
    //   rank: 4,
    //   discount: true,
    //   stock: 1,
    //   totalAddedToCart: 0,
    // },

    // {
    //   id: 2,
    //   image1: 'assets/imgs/itens/oculos-MATRIX.webp',
    //   // image2: 'assets/imgs/itens/oculos-MATRIX3.webp',
    //   name: 'Óculos Neo',
    //   movie: 'Matrix',
    //   description: 'óculos usado pelo personagem nas cenas x, x e x',
    //   price: 1200.0,
    //   rank: 2,
    //   discount: false,
    //   stock: 1,
    //   totalAddedToCart: 0,
    // },

    // {
    //   id: 3,
    //   image1: 'assets/imgs/itens/bolsa - AS BRANQUELAS.webp',
    //   // image2: 'assets/imgs/itens/as branquelas3.gif',
    //   name: 'bolsa',
    //   movie: 'As branquelas',
    //   description: 'bolsa usada pela personagem nas cenas x, x e x',
    //   price: 700.0,
    //   rank: 1,
    //   discount: true,
    //   stock: 1,
    //   totalAddedToCart: 0,
    // },